- name: Listeyi Diger Depoya Gonder (Push)
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # 1. Adım: İkinci deponu (AkcagozTV_Canli) bilgisayara gizlice indiriyoruz
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/batuhansabri55/AkcagozTV_Canli.git dondurulen_depo
        
        # 2. Adım: Az önce kodun ürettiği taze 'tr.m3u' dosyasını bu deponun içine kopyalıyoruz
        cp tr.m3u dondurulen_depo/tr.m3u
        
        # 3. Adım: İkinci depoya girip yeni listeyi yüklüyoruz
        cd dondurulen_depo
        git add tr.m3u
        git commit -m "Canlı Türkçe Listesi Güncellendi" || exit 0
        git push
